# -*- coding: utf-8 -*-
"""num2txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xyKGfiQeTzUguuxWmxs8ARX79r1LuEa
"""

#define all the numbers in word
def txt(num) :

    d = {0:"zero",1:"one",2:"two",3:"three",4:"four",5:"five",6:"six",7:"seven",8:"eight",9:"nine",
        10:"ten",11:"eleven",12:"twelve",13:"thirteen",14:"fourteen",15:"fifteen",16:"sixteen",
        17:"seventeen",18:"eighteen",19:"nineteen",20:"twenty",30:"thirty",40:"forty",50:"fifty",
        60:"sixty",70:"seventy",80:"eighty",90:"ninety",100:"hundred"
        }

    #to ensure the number is in the range 0 - 99999
    assert 0<= num <= 99999, "Number not within the range"

    if num <= 20:
      return d[num]

    elif (num < 100):
      if num % 10 == 0:
        return d[num]
      else:
        return d[num // 10 *10] + "-" + d[num % 10]

    elif (num < 1000):
      if num%100 == 0:
        return d[num // 100] + " hundred"
      else:
        #use txt() function here so it convert 62 to sixty-two directly, it is recursive - it can call itself to handle smaller parts of number
        return d[num // 100] + " hundred and " + txt(num % 100)

    elif (num < 100000):
      thousands = txt(num // 1000)
      remainder = num % 1000
      if remainder == 0:
        return thousands + " thousand"
      elif remainder < 100:
        return thousands + " thousand and " + txt(remainder)
      else:
        return thousands + " thousand, " + txt(remainder)